version: "2"
services:
  app:
    build:
      # Build an image from the Dockerfile in the current directory
      context: .
    ports:
      - 8080:8080
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      REDIS_HOST: "epython-dash-demo.bqvjwk.ng.0001.euw1.cache.amazonaws.com"
